### ISSUE TITLE
linux installer

### ISSUE THREAD

**Issue by attuska** [lgblgblgb/ep128emu#3]
Nincs linux installer, csak windows!
Kellne egy normális Makefile, mely nem csak a binárisok elkészítésére szolgálna, hannem az elkészült cuccok és resources dolgok telepítésére is.
A mostani scons szkript csak a fordításhoz használható.
A Makefile természetesen generátorral is elkészíthető lehetne, mondkuk a cmake -val, melyhez természetesen Cmakefiles.txt -ek kellenének. Ezek sem értek sajna sok egyéb közt.

Nekem van egy bash intall szkriptem a fordítás utáni telepítéshez, de ez túl specifikus.

> #!/bin/sh -eux

DESTDIR="$UB_INSTALLDIR"
BINDIR="$DESTDIR"/usr/bin
DATADIR="$DESTDIR"/usr/share/ep128
PIXMAPDIR="$DESTDIR"/usr/share/pixmaps
DESKTOPDIR="$DESTDIR"/usr/share/applications

#célkönyvtárak
mkdir -p "$BINDIR" "$PIXMAPDIR" "$DESKTOPDIR" "$DATADIR"/{roms,disk,config}

mv ep128emu_roms.bin roms/
cp -r roms config disk "$DATADIR"/
cp resource/*.desktop "$DESKTOPDIR"/
cp ep128emu tapeedit resource/{zx128emu,cpc464emu} "$BINDIR"/

#ico fájlok konverziója
convert resource/ep128emu.ico $PIXMAPDIR/ep128emu.png
convert resource/zx128emu.ico $PIXMAPDIR/zx128emu.png
convert resource/cpc464em.ico $PIXMAPDIR/cpc464emu.png
convert resource/tapeedit.ico $PIXMAPDIR/tapeedit.png

#makecfg wrapper célja
mv makecfg "$DATADIR"/makecfg.bin

**Comment by attuska** [comment]
A /usr/bin/makecfg szkript:

> #!/bin/bash

if test ! -d ~/.ep128emu/roms
then
mkdir -p ~/.ep128emu/roms
cp /usr/share/ep128/roms/ep128emu_roms.bin ~/.ep128emu/roms
fi
/usr/share/ep128/makecfg.bin

**Comment by lgblgblgb** [comment]
Es a ep128emu_roms.bin az hogyan all elo?

**Comment by attuska** [comment]
Nos egy újabb vadászat!

Magyarázat a makecfg szkripthez.

Nyilván nem szabad zargatni a júzert azzal, hogy ő maga vadássza le és ráadásul jó helyre a nélkülözhetetlen romhalmazt.

Innen szedi le a romokat a csomagkészítőm letöltője a csomagkészítés kezdetén:
http://ep128emu.enterpriseforever.com/roms/ep128emu_roms.bin
Ezt az én kézzel-lábbal bash szkripttel írt telepítőm elrakja a normális $DATADIR helyre, a $DESTDIR/usr/share/ep128/ alá a roms könyvtárba. A csomag feltelepítése után eme romhalmaz már a /usr/share/ep128/roms alatt található.

István makecfg okosságát átneveztem makecfg.bin -re és ezt a szabványosnak mondható $DATADIR alá raktam.

Ebből fogja majd ugye a makecfg szkript elrakni a júzer ~ könyvtárába ezt a már a feltelepített rendszeren lévő romhalmazt.
Ezután az ep128emu első indulákor le akarná majd futtatni a makecfg okosságot, de helyette ott leli az én wrapperemet, ami először elővadássza és jó helyre teszi a romhalmazt, ezután futtatja a makecfg.bin okosságot, mely a romhalmazból kibontogatja a romokat, utána máris vígan fut az emu.

Most jó lenne, ha ennek a romhalmaz binárisnak letöltését (575 Kb) nem maga a leendő Makefile, vagy valami más installer csinálná mondjuk a wget -tel, vagy bármi más nethasználó cuccal, hanem elérhető lenne közvetlen itt az emu forrásában. Nálunk más a helyzet, mint a DEBIAN, vagy Arch, vagy Gentoo, vagy Redhat alapú rendszereknél. A chroot alatti csomagkészítéskor ugyanis nincs inicializált hálózat, grafika sem, tehát a wget sem működik, mivel az a környezet csakis egy minimális, a fordításhoz nélkülözhetetlen cuccokkból áll, ott már minden szükséges fájlnak helyileg elérhetőnek kell lennie. Ha ezt a letöltést a leendő installer csinálja, azt én úgyis meg fogom magamnak patkolni és kiirtom disztróspecifikumom miatt belőle és az installer meghívása előtt már tálcán fogom nyújtani a chroot felépítése és abba való belépés előtt a már letöltött romhalmazt.
A github nem igazán a binárisok tárolására lett kitalálva, de azt hiszem még ez a romhalmaz belefér, ez könyebb helyzetet teremtene, mert akkor a letöltött forráshalmazban már ez is benne lenne.

**Comment by lgblgblgb** [comment]
Ezzel viszont - ne haragudj - de nem ertek egyet. Ez licenc szempontjabol is problemas, mivel ugye pl az EXOS nem GNU/GPL es eleve csak binaris, szoval a kozismert "binary blob" esete ... Debian-ban itt max kulon csomagot csinalnak a data file-ra (pl ep128emu-data) ami a non-free szekcioban van. A Xep128 eseten pl nekem az a tervem, hogy maga az emulator fel fogja ajanlani majd, hogy o letolti, ha nem talalja. ep128emu eseten meg ugyis ott a makecfg, mi lenne, ha az le is tolteni a "cp" helyett, hogy atmasolja a usernek?

**Comment by lgblgblgb** [comment]
Meg hozztennem: elkepzelheto, hogy mar jogi problema nem merulne amugy fel (amit irtal forumon is epp most olvastam), amde akkor sem illik az emulator licencehez ettol meg.

**Comment by attuska** [comment]
A logika szerint ekkor viszont már a mindenki által letölthető http://ep128emu.enterpriseforever.com/roms/ep128emu_roms.bin bináris letöltése is eleve licensz bajos.
Talán kellne egy LICENSE fájlt mellékelni az egész rom cucchoz.
Nem tudom, hogy az egyes romoknak most milyen a licensz állapotuk.

**Comment by lgblgblgb** [comment]
A kulcs az, hogy nincs _egybe_ csomagolva egy GNU/GPL-el felcimkezett projecttel :) Tehat, az hogy kulon letoltheto stb, az egy dolog. Szerintem nem veletlen hogy a Debian sem tesz mindent egyben, meg mas emulatoroknal sem szokas feltetlen, es a userre van bizva ... Mert ha ki is rakod az oldalra, akkor fel lehet ugy fogni, hogy a user dontott ugy, hogy letolti. De ha csinalsz egy csomagot belole, foleg forraskod szinten ami GNU/GPL, az erzesem szerint problema. Szerintem nem igazan szokas is, mindent egyben csinalni a dolgot. Most tenyleg nem kotekedni akarok am, valoszinuleg a kutyat nem izgatja mar az EP ROM-ok jogi kerdese, ez inkabb elvi szintu tema ... Amugy az miert nem jo, amit javasoltam? Ha mar ott az a wrapper script a makecfg-hez, es o is csak masolja a user potty-config dirjebe, miert ne tolthetne le a masolas helyett, es akkor nem kell sehova betenni :)

**Comment by attuska** [comment]
Ez a wrapper wget jó ötlet! Nem kell cp, hanem wget. Csak abba bele kellne tenni valami hibafigyelést, ha beletörne a bicskája, rinyákoljon.
Most valahogy törölni szeretném a PR -t, ezen vagyok.

**Comment by lgblgblgb** [comment]
Lezartam merge nelkul a PR-t, igy jo lesz?

**Comment by attuska** [comment]
Biztosan.
Megtanultam visszacsinálni egy committomat legalább.
Ha nem tudom szinkronizálni a forkomat, akkor lehet, hogy törlöm és csinálok inkább egy újat.

**Comment by lgblgblgb** [comment]
Speciel nem igazan teszteltem, de lasd ezt a commit-ot: b4988f2c71956bc061d601f09182037a96971036

Elvileg ezek utan eleg ez az egy szem cucc:

make install IPREFIX=$UB_INSTALLDIR/usr

Az /usr resz fontos :) Alapbol az /usr -t nem akartam beletenni, ui ha nem distrib-be csinalod, ugye az install altalaban az /usr/local -t jelenti. Igy viszont kisse utkozne. Igy most a Makefile-ban az IPREFIX ugyan /usr/local, de ha a fenti modon megmondod a make-nek, hogy neked mas legyen, akkor az lesz.

Tovabba a makecfg-rol: nekem nem tetszett a neve ... Ez menne esetleg az /usr/bin-be ilyen altalanos nevvel, ami azert kisse zavaro ... Ezert atneveztem, install utan makecfg-ep128emu lesz. Ez hivja a szinten mellette levo makecfg-ep128emu.bin -t (az elobbi a wrapper, az utana levo a "valodi" ELF binaris). Igy nem kell kulon dir-be tenni (a nevek csak a vegeben kulonboznek), es nem kell heursztika, hogy most IPREFIX alapjan varazslat, hogy hol is van meg installer irja at stb. Plusz en /usr/share es hasonlok ala nem is szivesen tennek binarist valahogy. Ez amugy, ha jol remlik, talan Debianeknal is divat neha, igaz ott .real szokott lenni, vagy nem is tudom.

**Comment by attuska** [comment]
Letesztelem.

**Comment by lgblgblgb** [comment]
Ezt lezarhatom? A "nincs" installer mar nem igaz :D Ha meg gond van vele, az mar nem a "nincs :) :)

**Comment by attuska** [comment]
Szerintem jó, hogy lezártad.
